apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

labels:
- pairs:
   app.kubernetes.io/name: argocd-applicationset
   app.kubernetes.io/instance: argocd-applicationset
   app.kubernetes.io/part-of: argocd
  includeTemplates: true

resources:
- ./appset.yaml
