apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- pairs:
    app.kubernetes.io/name: workload1
    app.kubernetes.io/instance: workload1
  includeSelectors: true

resources:
- ./deployment.yaml

configMapGenerator:
- name: workload1-env
  literals:
  # - <key>=<value>

components:
- ../../../components/set-ndots/
- ../../../components/append-apache-exporter-sidecar
