apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- pairs:
    app.kubernetes.io/instance: workload1-foo
  includeSelectors: true
# - pairs:
#     app.kubernetes.io/version: <TBD>
#   includeTemplates: true

resources:
- ../../../../bases/workload1/deployment/

configMapGenerator:

secretGenerator:

components:

patches:
