apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- pairs:
    app.kubernetes.io/name: workload1
    app.kubernetes.io/instance: workload1
  includeSelectors: true

resources:
- ./deployment/
- ./service.yaml
