apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- path: ./deployment.patch.yaml
  target:
    kind: Deployment

images:
- name: apache-exporter
  newName: XXXX/apache-exporter
  newTag: YYYY
